### ISSUE TITLE
Didn't work in Android 12 DP4

### ISSUE THREAD

**Issue by brownursidaeR** [KieronQuinn/DiscoverKiller#4]
didn't work on Android 12 beta4 both custom app or update page

If need any log i would provide

**Comment by FrzMtrsprt** [comment]
Same here with LSPosed on Android 12, the module tells me to enable it for itself, but you can't hook the module itself on LSPosed.

**Comment by KieronQuinn** [comment]
> Same here with LSPosed on Android 12, the module tells me to enable it for itself, but you can't hook the module itself on LSPosed.

LSposed automatically hooks the module itself. The check is a "self-hook", it not working suggests LSposed itself isn't working properly.

As part of the bugfix release (which will go out tomorrow), I've added a delay to the check, hoping that it's just LSposed being slow to setup the hooks on 12. If it's not, I'm told by other users that you can just relaunch the app a few times and it'll start working.

The overlay issue on 12 is also fixed in the bugfix.

**Comment by KieronQuinn** [comment]
Fixed in 2.1

**Comment by FrzMtrsprt** [comment]
The problem seems to persist on 2.1, and relaunching the app a few times doesn't solve the problem.

**Comment by KieronQuinn** [comment]
> The problem seems to persist on 2.1, and relaunching the app a few times doesn't solve the problem.

I don't think there's anything I can do that doesn't involve introducing a bypass or removing the check entirely then. I'd rather avoid removing the check entirely as it would just lead to confused people, but maybe I could add a bypass with a hidden button or something

**Comment by FrzMtrsprt** [comment]
A "Continue anyway" button would be nice.2021年8月21日 22:29，Kieron Quinn ***@***.***>写道：

The problem seems to persist on 2.1, and relaunching the app a few times doesn't solve the problem.

I don't think there's anything I can do that doesn't involve introducing a bypass or removing the check entirely then. I'd rather avoid removing the check entirely as it would just lead to confused people, but maybe I could add a bypass with a hidden button or something

**Comment by KieronQuinn** [comment]
Version 2.2 removes the delay added in 2.1 and adds an option to bypass the check.
